---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes

  - name: install apache2 pak
    apt:
      name: apache2
      state: absent

  - name: add php support and blah shit
    apt:
      name: libapache2-mod-php
      state: absent

